### ISSUE TITLE
Python M/M/1 Example showing Empty Dataframe

### ISSUE THREAD

**Issue by joolink** [imperial-qore/line-solver#1]
Hello,
I installed line-solver and the dependencies (from requirements.txt) via pip and copied your example from the README.
Now I am getting the answer:

Empty DataFrame
Columns: [Station, JobClass, QLen, Util, RespT, ResidT, ArvR, Tput]
Index: []

Shouldn't that show me values for the configured queue?
Regards

**Comment by gcasale** [comment]
That's strange we will check asap and revert with a fix.

**Comment by gcasale** [comment]
Hi,
I cloned on windows the repo, then pip install -r requirements.txt, and thenI append the following commands to mm1.py in the root:
``
    print(table.loc[1].ArvR)
    print(tget(table,"Queue").Tput)
``
launching python3 mm1.py I get
``
JMT Model: C:\Users\gcasale.WIN\AppData\Local\Temp\workspace\jsim\11980108622583401784\model.jsim
JMT Analysis completed. Runtime: 1.179 seconds
  Station JobClass      QLen      Util     RespT    ResidT      ArvR      Tput
0  Source   Class1  0.000000  0.000000  0.000000  0.000000  0.000000  1.003336
1   Queue   Class1  1.003966  0.512017  1.047643  1.047643  1.003336  1.003028
1.0033356633373225
  Station JobClass      QLen      Util     RespT    ResidT      ArvR      Tput
1   Queue   Class1  1.003966  0.512017  1.047643  1.047643  1.003336  1.003028
1    1.003028
Name: Tput, dtype: float64
``
So all seems OK on my PC. What commands do you do specifically?
